export interface Surah {
    id: number;
    name: string;
    transliteration: string;
    type: 'Meccan' | 'Medinan';
    totalAyahs: number;
    juz: number[];
}

export const quranData: Surah[] = [
    { id: 1, name: "الفاتحة", transliteration: "Al-Fatihah", type: "Meccan", totalAyahs: 7, juz: [1] },
    { id: 2, name: "البقرة", transliteration: "Al-Baqarah", type: "Medinan", totalAyahs: 286, juz: [1, 2, 3] },
    { id: 3, name: "آل عمران", transliteration: "Ali 'Imran", type: "Medinan", totalAyahs: 200, juz: [3, 4] },
    { id: 4, name: "النساء", transliteration: "An-Nisa", type: "Medinan", totalAyahs: 176, juz: [4, 5, 6] },
    { id: 5, name: "المائدة", transliteration: "Al-Ma'idah", type: "Medinan", totalAyahs: 120, juz: [6, 7] },
    { id: 6, name: "الأنعام", transliteration: "Al-An'am", type: "Meccan", totalAyahs: 165, juz: [7, 8] },
    { id: 7, name: "الأعراف", transliteration: "Al-A'raf", type: "Meccan", totalAyahs: 206, juz: [8, 9] },
    { id: 8, name: "الأنفال", transliteration: "Al-Anfal", type: "Medinan", totalAyahs: 75, juz: [9, 10] },
    { id: 9, name: "التوبة", transliteration: "At-Tawbah", type: "Medinan", totalAyahs: 129, juz: [10, 11] },
    { id: 10, name: "يونس", transliteration: "Yunus", type: "Meccan", totalAyahs: 109, juz: [11] },
    { id: 11, name: "هود", transliteration: "Hud", type: "Meccan", totalAyahs: 123, juz: [11, 12] },
    { id: 12, name: "يوسف", transliteration: "Yusuf", type: "Meccan", totalAyahs: 111, juz: [12, 13] },
    { id: 13, name: "الرعد", transliteration: "Ar-Ra'd", type: "Medinan", totalAyahs: 43, juz: [13] },
    { id: 14, name: "ابراهيم", transliteration: "Ibrahim", type: "Meccan", totalAyahs: 52, juz: [13] },
    { id: 15, name: "الحجر", transliteration: "Al-Hijr", type: "Meccan", totalAyahs: 99, juz: [14] },
    { id: 16, name: "النحل", transliteration: "An-Nahl", type: "Meccan", totalAyahs: 128, juz: [14] },
    { id: 17, name: "الإسراء", transliteration: "Al-Isra", type: "Meccan", totalAyahs: 111, juz: [15] },
    { id: 18, name: "الكهف", transliteration: "Al-Kahf", type: "Meccan", totalAyahs: 110, juz: [15, 16] },
    { id: 19, name: "مريم", transliteration: "Maryam", type: "Meccan", totalAyahs: 98, juz: [16] },
    { id: 20, name: "طه", transliteration: "Ta-Ha", type: "Meccan", totalAyahs: 135, juz: [16] },
    { id: 21, name: "الأنبياء", transliteration: "Al-Anbiya", type: "Meccan", totalAyahs: 112, juz: [17] },
    { id: 22, name: "الحج", transliteration: "Al-Hajj", type: "Medinan", totalAyahs: 78, juz: [17] },
    { id: 23, name: "المؤمنون", transliteration: "Al-Mu'minun", type: "Meccan", totalAyahs: 118, juz: [18] },
    { id: 24, name: "النور", transliteration: "An-Nur", type: "Medinan", totalAyahs: 64, juz: [18] },
    { id: 25, name: "الفرقان", transliteration: "Al-Furqan", type: "Meccan", totalAyahs: 77, juz: [18, 19] },
    { id: 26, name: "الشعراء", transliteration: "Ash-Shu'ara", type: "Meccan", totalAyahs: 227, juz: [19] },
    { id: 27, name: "النمل", transliteration: "An-Naml", type: "Meccan", totalAyahs: 93, juz: [19, 20] },
    { id: 28, name: "القصص", transliteration: "Al-Qasas", type: "Meccan", totalAyahs: 88, juz: [20] },
    { id: 29, name: "العنكبوت", transliteration: "Al-'Ankabut", type: "Meccan", totalAyahs: 69, juz: [20, 21] },
    { id: 30, name: "الروم", transliteration: "Ar-Rum", type: "Meccan", totalAyahs: 60, juz: [21] },
    { id: 31, name: "لقمان", transliteration: "Luqman", type: "Meccan", totalAyahs: 34, juz: [21] },
    { id: 32, name: "السجدة", transliteration: "As-Sajdah", type: "Meccan", totalAyahs: 30, juz: [21] },
    { id: 33, name: "الأحزاب", transliteration: "Al-Ahzab", type: "Medinan", totalAyahs: 73, juz: [21, 22] },
    { id: 34, name: "سبأ", transliteration: "Saba", type: "Meccan", totalAyahs: 54, juz: [22] },
    { id: 35, name: "فاطر", transliteration: "Fatir", type: "Meccan", totalAyahs: 45, juz: [22] },
    { id: 36, name: "يس", transliteration: "Ya-Sin", type: "Meccan", totalAyahs: 83, juz: [22, 23] },
    { id: 37, name: "الصافات", transliteration: "As-Saffat", type: "Meccan", totalAyahs: 182, juz: [23] },
    { id: 38, name: "ص", transliteration: "Sad", type: "Meccan", totalAyahs: 88, juz: [23] },
    { id: 39, name: "الزمر", transliteration: "Az-Zumar", type: "Meccan", totalAyahs: 75, juz: [23, 24] },
    { id: 40, name: "غافر", transliteration: "Ghafir", type: "Meccan", totalAyahs: 85, juz: [24] },
    { id: 41, name: "فصلت", transliteration: "Fussilat", type: "Meccan", totalAyahs: 54, juz: [24, 25] },
    { id: 42, name: "الشورى", transliteration: "Ash-Shura", type: "Meccan", totalAyahs: 53, juz: [25] },
    { id: 43, name: "الزخرف", transliteration: "Az-Zukhruf", type: "Meccan", totalAyahs: 89, juz: [25] },
    { id: 44, name: "الدخان", transliteration: "Ad-Dukhan", type: "Meccan", totalAyahs: 59, juz: [25] },
    { id: 45, name: "الجاثية", transliteration: "Al-Jathiyah", type: "Meccan", totalAyahs: 37, juz: [25] },
    { id: 46, name: "الأحقاف", transliteration: "Al-Ahqaf", type: "Meccan", totalAyahs: 35, juz: [26] },
    { id: 47, name: "محمد", transliteration: "Muhammad", type: "Medinan", totalAyahs: 38, juz: [26] },
    { id: 48, name: "الفتح", transliteration: "Al-Fath", type: "Medinan", totalAyahs: 29, juz: [26] },
    { id: 49, name: "الحجرات", transliteration: "Al-Hujurat", type: "Medinan", totalAyahs: 18, juz: [26] },
    { id: 50, name: "ق", transliteration: "Qaf", type: "Meccan", totalAyahs: 45, juz: [26] },
    { id: 51, name: "الذاريات", transliteration: "Adh-Dhariyat", type: "Meccan", totalAyahs: 60, juz: [26, 27] },
    { id: 52, name: "الطور", transliteration: "At-Tur", type: "Meccan", totalAyahs: 49, juz: [27] },
    { id: 53, name: "النجم", transliteration: "An-Najm", type: "Meccan", totalAyahs: 62, juz: [27] },
    { id: 54, name: "القمر", transliteration: "Al-Qamar", type: "Meccan", totalAyahs: 55, juz: [27] },
    { id: 55, name: "الرحمن", transliteration: "Ar-Rahman", type: "Medinan", totalAyahs: 78, juz: [27] },
    { id: 56, name: "الواقعة", transliteration: "Al-Waqi'ah", type: "Meccan", totalAyahs: 96, juz: [27] },
    { id: 57, name: "الحديد", transliteration: "Al-Hadid", type: "Medinan", totalAyahs: 29, juz: [27] },
    { id: 58, name: "المجادلة", transliteration: "Al-Mujadilah", type: "Medinan", totalAyahs: 22, juz: [28] },
    { id: 59, name: "الحشر", transliteration: "Al-Hashr", type: "Medinan", totalAyahs: 24, juz: [28] },
    { id: 60, name: "الممتحنة", transliteration: "Al-Mumtahanah", type: "Medinan", totalAyahs: 13, juz: [28] },
    { id: 61, name: "الصف", transliteration: "As-Saff", type: "Medinan", totalAyahs: 14, juz: [28] },
    { id: 62, name: "الجمعة", transliteration: "Al-Jumu'ah", type: "Medinan", totalAyahs: 11, juz: [28] },
    { id: 63, name: "المنافقون", transliteration: "Al-Munafiqun", type: "Medinan", totalAyahs: 11, juz: [28] },
    { id: 64, name: "التغابن", transliteration: "At-Taghabun", type: "Medinan", totalAyahs: 18, juz: [28] },
    { id: 65, name: "الطلاق", transliteration: "At-Talaq", type: "Medinan", totalAyahs: 12, juz: [28] },
    { id: 66, name: "التحريم", transliteration: "At-Tahrim", type: "Medinan", totalAyahs: 12, juz: [28] },
    { id: 67, name: "الملك", transliteration: "Al-Mulk", type: "Meccan", totalAyahs: 30, juz: [29] },
    { id: 68, name: "القلم", transliteration: "Al-Qalam", type: "Meccan", totalAyahs: 52, juz: [29] },
    { id: 69, name: "الحاقة", transliteration: "Al-Haqqah", type: "Meccan", totalAyahs: 52, juz: [29] },
    { id: 70, name: "المعارج", transliteration: "Al-Ma'arij", type: "Meccan", totalAyahs: 44, juz: [29] },
    { id: 71, name: "نوح", transliteration: "Nuh", type: "Meccan", totalAyahs: 28, juz: [29] },
    { id: 72, name: "الجن", transliteration: "Al-Jinn", type: "Meccan", totalAyahs: 28, juz: [29] },
    { id: 73, name: "المزمل", transliteration: "Al-Muzzammil", type: "Meccan", totalAyahs: 20, juz: [29] },
    { id: 74, name: "المدثر", transliteration: "Al-Muddaththir", type: "Meccan", totalAyahs: 56, juz: [29] },
    { id: 75, name: "القيامة", transliteration: "Al-Qiyamah", type: "Meccan", totalAyahs: 40, juz: [29] },
    { id: 76, name: "الانسان", transliteration: "Al-Insan", type: "Medinan", totalAyahs: 31, juz: [29] },
    { id: 77, name: "المرسلات", transliteration: "Al-Mursalat", type: "Meccan", totalAyahs: 50, juz: [29] },
    { id: 78, name: "النبأ", transliteration: "An-Naba", type: "Meccan", totalAyahs: 40, juz: [30] },
    { id: 79, name: "النازعات", transliteration: "An-Nazi'at", type: "Meccan", totalAyahs: 46, juz: [30] },
    { id: 80, name: "عبس", transliteration: "'Abasa", type: "Meccan", totalAyahs: 42, juz: [30] },
    { id: 81, name: "التكوير", transliteration: "At-Takwir", type: "Meccan", totalAyahs: 29, juz: [30] },
    { id: 82, name: "الانفطار", transliteration: "Al-Infitar", type: "Meccan", totalAyahs: 19, juz: [30] },
    { id: 83, name: "المطففين", transliteration: "Al-Mutaffifin", type: "Meccan", totalAyahs: 36, juz: [30] },
    { id: 84, name: "الانشقاق", transliteration: "Al-Inshiqaq", type: "Meccan", totalAyahs: 25, juz: [30] },
    { id: 85, name: "البروج", transliteration: "Al-Buruj", type: "Meccan", totalAyahs: 22, juz: [30] },
    { id: 86, name: "الطارق", transliteration: "At-Tariq", type: "Meccan", totalAyahs: 17, juz: [30] },
    { id: 87, name: "الأعلى", transliteration: "Al-A'la", type: "Meccan", totalAyahs: 19, juz: [30] },
    { id: 88, name: "الغاشية", transliteration: "Al-Ghashiyah", type: "Meccan", totalAyahs: 26, juz: [30] },
    { id: 89, name: "الفجر", transliteration: "Al-Fajr", type: "Meccan", totalAyahs: 30, juz: [30] },
    { id: 90, name: "البلد", transliteration: "Al-Balad", type: "Meccan", totalAyahs: 20, juz: [30] },
    { id: 91, name: "الشمس", transliteration: "Ash-Shams", type: "Meccan", totalAyahs: 15, juz: [30] },
    { id: 92, name: "الليل", transliteration: "Al-Layl", type: "Meccan", totalAyahs: 21, juz: [30] },
    { id: 93, name: "الضحى", transliteration: "Ad-Duha", type: "Meccan", totalAyahs: 11, juz: [30] },
    { id: 94, name: "الشرح", transliteration: "Ash-Sharh", type: "Meccan", totalAyahs: 8, juz: [30] },
    { id: 95, name: "التين", transliteration: "At-Tin", type: "Meccan", totalAyahs: 8, juz: [30] },
    { id: 96, name: "العلق", transliteration: "Al-'Alaq", type: "Meccan", totalAyahs: 19, juz: [30] },
    { id: 97, name: "القدر", transliteration: "Al-Qadr", type: "Meccan", totalAyahs: 5, juz: [30] },
    { id: 98, name: "البينة", transliteration: "Al-Bayyinah", type: "Medinan", totalAyahs: 8, juz: [30] },
    { id: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", type: "Medinan", totalAyahs: 8, juz: [30] },
    { id: 100, name: "العاديات", transliteration: "Al-'Adiyat", type: "Meccan", totalAyahs: 11, juz: [30] },
    { id: 101, name: "القارعة", transliteration: "Al-Qari'ah", type: "Meccan", totalAyahs: 11, juz: [30] },
    { id: 102, name: "التكاثر", transliteration: "At-Takathur", type: "Meccan", totalAyahs: 8, juz: [30] },
    { id: 103, name: "العصر", transliteration: "Al-'Asr", type: "Meccan", totalAyahs: 3, juz: [30] },
    { id: 104, name: "الهمزة", transliteration: "Al-Humazah", type: "Meccan", totalAyahs: 9, juz: [30] },
    { id: 105, name: "الفيل", transliteration: "Al-Fil", type: "Meccan", totalAyahs: 5, juz: [30] },
    { id: 106, name: "قريش", transliteration: "Quraysh", type: "Meccan", totalAyahs: 4, juz: [30] },
    { id: 107, name: "الماعون", transliteration: "Al-Ma'un", type: "Meccan", totalAyahs: 7, juz: [30] },
    { id: 108, name: "الكوثر", transliteration: "Al-Kawthar", type: "Meccan", totalAyahs: 3, juz: [30] },
    { id: 109, name: "الكافرون", transliteration: "Al-Kafirun", type: "Meccan", totalAyahs: 6, juz: [30] },
    { id: 110, name: "النصر", transliteration: "An-Nasr", type: "Medinan", totalAyahs: 3, juz: [30] },
    { id: 111, name: "المسد", transliteration: "Al-Masad", type: "Meccan", totalAyahs: 5, juz: [30] },
    { id: 112, name: "الاخلاص", transliteration: "Al-Ikhlas", type: "Meccan", totalAyahs: 4, juz: [30] },
    { id: 113, name: "الفلق", transliteration: "Al-Falaq", type: "Meccan", totalAyahs: 5, juz: [30] },
    { id: 114, name: "الناس", transliteration: "An-Nas", type: "Meccan", totalAyahs: 6, juz: [30] }
];

export const getJuzSurahs = (juzNumber: number) => {
    return quranData.filter(surah => surah.juz.includes(juzNumber));
};
